const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_BILLING: 'MANAGE_BILLING',
  MANAGE_TASKS: 'MANAGE_TASKS',
  MANAGE_TEAMS: 'MANAGE_TEAMS',
};

const ROLES = {
  SUPER_ADMIN: 'SuperAdmin',
  ADMIN: 'Admin',
  PROJECT_MANAGER: 'ProjectManager',
  TEAM_MEMBER: 'TeamMember',
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.MANAGE_TEAMS,
  ],
  [ROLES.PROJECT_MANAGER]: [
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.MANAGE_TEAMS,
  ],
  [ROLES.TEAM_MEMBER]: [
    PERMISSIONS.MANAGE_TASKS,
  ],
};

const hasPermission = (role, permission) => {
  return ROLE_PERMISSIONS[role]?.includes(permission) || false;
};

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
  hasPermission,
};
